apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-builder

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ns-builder
  template:
    metadata:
      labels:
        app: ns-builder
    spec:
      volumes:
        - name: ns-bin
          emptyDir: {}
        - name: socket
          emptyDir: {}
        - name: config
          configMap:
            name: ns-config
        - name: known-hosts
          configMap:
            name: known-hosts

      initContainers:
        - name: buildpack-install
          image: ghcr.io/traptitech/ns-builder:main
          imagePullPolicy: Never
          command:
            - cp
            - /app/ns
            - /ns-bin
          volumeMounts:
            - mountPath: /ns-bin
              name: ns-bin

      containers:
        - name: buildpack
          image: paketobuildpacks/builder-jammy-full:latest
          imagePullPolicy: Always
          command:
            - /ns-bin/ns
            - buildpack-helper
          args:
            - --loglevel=debug
            - --config=/opt/config/ns.yaml
          volumeMounts:
            - mountPath: /ns-bin
              name: ns-bin
            - mountPath: /opt/config/ns.yaml
              name: config
              subPath: ns.yaml

        - name: buildkitd
          image: moby/buildkit:latest
          imagePullPolicy: Always
          args:
            - --addr
            - unix:///run/buildkit/buildkitd.sock
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /run/buildkit
              name: socket
            - mountPath: /etc/buildkit/buildkitd.toml
              name: config
              subPath: buildkitd.toml

        - name: builder
          image: ghcr.io/traptitech/ns-builder:main
          imagePullPolicy: Never
          args:
            - --loglevel=debug
            - --config=/opt/config/ns.yaml
          envFrom:
            - configMapRef:
                name: custom-config
            - secretRef:
                name: token
          volumeMounts:
            - mountPath: /run/buildkit
              name: socket
            - mountPath: /opt/config/ns.yaml
              name: config
              subPath: ns.yaml
            - mountPath: /root/.ssh/known_hosts
              name: known-hosts
              subPath: known_hosts
