apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system

data:
  # For local development: resolve "registry.local" to host ip
  # k3d default + rewrite plugin
  # see https://zenn.dev/toshikish/articles/7f555dbf1b4b7d for rewrite plugin
  Corefile: |
    .:53 {
        rewrite name registry.local host.k3d.internal
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
