resources:
  - builder-deployment.yaml
  - coredns-configmap.yaml

configMapGenerator:
  - name: known-hosts
    files:
      - ./config/known_hosts
  - name: ns-config
    files:
      - ./config/ns.yaml
      - ./config/buildkitd.toml
  - name: custom-config
    files:
      - NS_COMPONENTS_BUILDER_CONTROLLER_URL=./config/controller-url.txt

secretGenerator:
  - name: token
    files:
      - NS_COMPONENTS_CONTROLLER_TOKEN=./config/controller-token.txt
