services:
  ns-builder:
    image: ghcr.io/traptitech/ns-builder:main
    command: --debug --loglevel=trace --config=/config.yaml
    restart: always
    environment:
      NS_COMPONENTS_CONTROLLER_TOKEN:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # for buildpack docker backend
      - ./config.yaml:/config.yaml
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
    depends_on:
      buildkitd:
        condition: service_started
    extra_hosts:
      - host.docker.internal:host-gateway
      - registry.local:host-gateway

  buildpack:
    image: paketobuildpacks/builder-jammy-full:latest
    restart: always
    entrypoint:
      - sleep
      - infinity
    extra_hosts:
      - registry.local:host-gateway

  buildkitd:
    image: moby/buildkit:latest
    restart: always
    privileged: true
    command: --addr tcp://0.0.0.0:1234
    volumes:
      - ../buildkitd/buildkitd.toml:/etc/buildkit/buildkitd.toml
    extra_hosts:
      - registry.local:host-gateway
