components:
  builder:
    buildkit:
      address: tcp://buildkitd:1234
    buildpack:
      backend: docker
      docker:
        containerName: ext-builder-buildpack-1
        remoteDir: /workspace
        user: cnb
        group: cnb
        platformAPI: "0.11"
    controller:
      url: http://host.docker.internal:10000
    priority: 10
