apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: promtail

spec:
  targetNamespace: monitor
  repo: https://grafana.github.io/helm-charts
  chart: promtail
  version: "6.11.5"
  valuesContent: |-
    tolerations:
      - operator: Exists
    
    configmap:
      enabled: true
    
    config:
      clients:
        - url: http://loki.monitor.svc.cluster.local:3100/loki/api/v1/push
      snippets:
        extraRelabelConfigs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
            replacement: $1
